Update assemble

diff --git a/s2i/bin/assemble b/s2i/bin/assemble
--- a/s2i/bin/assemble
+++ b/s2i/bin/assemble
@@ -2,15 +2,78 @@
 
 set -e
 
-echo "---> Installing application source"
-cp -Rf /tmp/src/. ./
+# restore maven dependencies downloaded in a previous build,
+# so they do not have to be downloaded again.
+# /opt/s2i/destination/artifacts will only be present in the incremental build scenario
+# in which the target image name is an existing docker image which contains
+# dependencies from a prior build execution.
+function restore_saved_artifacts() {
+  if [ "$(ls -A /opt/s2i/destination/artifacts/ 2>/dev/null)" ]; then
+    echo -n "Restoring saved artifacts from prior build..."
+    mv /opt/s2i/destination/artifacts/* /opt/s2i/destination/artifacts/.[!.]* $HOME/.
+  fi
+}
 
-echo "---> Building Spring Boot application from source"
-if [ -f "mvnw" ]; then
-  ./mvnw clean install
+# Source code provided to S2I is at ${HOME}
+LOCAL_SOURCE_DIR=${HOME}
+mkdir -p $LOCAL_SOURCE_DIR
+
+
+if [ -f "$LOCAL_SOURCE_DIR/pom.xml" ]; then
+  # restore any maven dependencies which will be present if this is an
+  # incremental build
+  restore_saved_artifacts
+
+  pushd $LOCAL_SOURCE_DIR &> /dev/null
+
+  if [ -z "$MAVEN_ARGS" ]; then
+    export MAVEN_ARGS="clean install -DskipTests=true"
+  fi
+  if [ -n "$MAVEN_ARGS_APPEND" ]; then
+    export MAVEN_ARGS="$MAVEN_ARGS $MAVEN_ARGS_APPEND"
+  fi
+  echo "Found pom.xml... attempting to build with 'mvn ${MAVEN_ARGS}'"
+
+  mvn --version
+  mvn $MAVEN_ARGS
+
+  ERR=$?
+  if [ $ERR -ne 0 ]; then
+    echo "Aborting due to error code $ERR from mvn package"
+    exit $ERR
+  fi
+
+  echo "Copying built war files into $DEPLOY_DIR for later deployment..."
+  popd &> /dev/null
+
 else
-  mvn clean install
+  echo "Copying binaries in source directory into $DEPLOY_DIR for later deployment..."
+  cp $LOCAL_SOURCE_DIR/*.war $DEPLOY_DIR >& /dev/null
+  chgrp -R 0 $DEPLOY_DIR
+  chmod -R g+rw $DEPLOY_DIR
 fi
 
+if [ -d $LOCAL_SOURCE_DIR/target ]; then
+  cp $LOCAL_SOURCE_DIR/target/*.war $DEPLOY_DIR >& /dev/null
+  chgrp -R 0 $DEPLOY_DIR
+  chmod -R g+rw $DEPLOY_DIR
+fi
+if [ -d $LOCAL_SOURCE_DIR/deployments ]; then
+  cp $LOCAL_SOURCE_DIR/deployments/*.war $DEPLOY_DIR >& /dev/null
+  chgrp -R 0 $DEPLOY_DIR
+  chmod -R g+rw $DEPLOY_DIR
+fi
+
+# sin almacenar m2 repo
+#echo "---> Installing application source"
+#cp -Rf /tmp/src/. ./
+
+#echo "---> Building Spring Boot application from source"
+#if [ -f "mvnw" ]; then
+#  ./mvnw clean install
+#else
+#  mvn clean install
+#fi
+
 # Fix source directory permissions
-fix-permissions ./
+#fix-permissions ./
